### PR TITLE
Nonuniform grid plots

### PR DESCRIPTION
**Pull request by manauref**
Add support for non-uniform grids (i.e. from using NonUniformRectCart in gkyl) in pgkyl data loading and interpolate. Tried 1x1v and 1x2v plots and animations and they look good. Also tried selecting 1D slices in 1x1v and they also look good.

Not adding reviewers for now, but @pcagas said it looked safe to merge.

### CODE REVIEW

**Comment by liangwang0734** [comment]
Does this work for fluid/field data using NonUniformRectGrid grid?

My test failed due to error like
```bash
  File "postgkyl/data/data.py", line 258, in _loadFrame
    lower[d] = self._grid[0][idx, d]
TypeError: list indices must be integers or slices, not tuple
```
Since the `self._grid[0]` itself is a list.

I was working on the commit b18e8dbf31b7547384363321a4196c3d8e01ebba to make sure it wasn't caused by anything I changes in the PR https://github.com/ammarhakim/gkyl/pull/66 and I ran the then-existing test `Regression/msphere3d-5m.lua` just to get the initial condition output file and tried
```bash
pgkyl -f msphere3d-5m_field_0.bp --comp 0 --z1 48 plot
```

Postgkyl 1.5.3 2021-06-05 (linux)

**Comment by JunoRavin** [comment]
Can you upgrade your postgkyl? 1.5.3 is fairly old at this point and you're still using the -f flag, which got deprecated back in February.

**Comment by liangwang0734** [comment]
I upgraded through conda but forgot to quit the session before trying.

After upgrading, the error is
```
  File "/home/liang/miniconda3/envs/cfd/lib/python3.8/site-packages/postgkyl/data/data.py", line 264, in _loadFrame
    lower[d] = self._grid[0][idx, d]
ValueError: setting an array element with a sequence.
```
Postgkyl 1.6.1 2021-04-13 (linux)

**Comment by ammarhakim** [comment]
You need to talk to Petr about this. Involve him in the discussion about
Pgkyl plotting and formats.

**Comment by liangwang0734** [comment]
Yes, @pcagas @manauref 

Do you think postgkyl can plot a 2d slice of 3d moment fluid/field data with NonUniformRectCart grid?

**Comment by liangwang0734** [comment]
I uploaded the file [here](https://drive.google.com/drive/folders/1z5f-umprmqZmM0kSoeQ44pUi7vUa17aF?usp=sharing).

My command looks like

```pgkyl msphere3d-5m_field_0.bp --component 0 --z1 48 plot
```
```
Postgkyl 1.6.1 2021-04-13 (linux)
postgkyl           gkyl/linux-64::postgkyl-1.6.5-py38_20210413
```

**Comment by pcagas** [comment]
I'll take a look

**Comment by pcagas** [comment]
@liangwang0734 there was a bug in the data.py where the partial loading function was misused. Additionally, the plot needed to be slightly modified.
This should be working now:
`pgkyl msphere3d-5m_field_0.bp --component 0 --z1 48 plot`
Pushing the changes now.

**Comment by liangwang0734** [comment]
@pcagas Yes, it works now! Thanks.

**Pull request merged**
